Add linters
jbrime15/Hello-Microverse pull request #1
Opened 2022-01-05 13:59 UTC by jbrime15

2022-01-05 15:31 UTC, jbrime15 commented
This project demonstrates how to use gitignore and Linters.

2022-01-05 16:28 UTC, Deepakdanger requested changes
Hi @jbrime15, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-05 16:28 UTC, Deepakdanger commented on README.md
> +![screenshot](./app_screenshot.png)
This screenshot is not displaying. Kindly fix this 🔧

2022-01-05 16:28 UTC, Deepakdanger commented on README.md
> +[Live Demo Link](https://livedemo.com)
This live demo link is broken. Kindly fix this. Your README is the entry point of your users and having it well written without any broken links gives a good first impression and maximizes the potential of your product to your users.

2022-01-05 16:28 UTC, Deepakdanger commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
It is good to have well descriptive author information. Kindly change it

2022-01-05 16:28 UTC, Deepakdanger commented on README.md
> +👤 **Author2**
Here `Author2` is displaying that is taking unnecessary attention, Please remove it.

2022-01-05 16:28 UTC, Deepakdanger commented on index.html
> +    <link rel="stylesheet" href="../Hello-Microverse-/styles.css">
Your CSS style is not displaying in your index.html. There is some issue with the CSS file address, Kindly fix this

2022-01-05 21:29 UTC, julie-ify approved these changes
## Hi @jbrime15, 

# Highlights
- Good job implementing the required changes from the previous reviewer ✔️ 

# Status: Approved ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved emoji](https://user-images.githubusercontent.com/81468675/147213535-ab80a883-5bf8-4284-b9ee-d90332328671.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-11 09:52 UTC, merged

2022-03-16 06:11 UTC, Mre55 reviewed
Hi @jbrime15, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :negative_squared_cross_mark:

You have submitted a project, that has been approved already. Kindly create a new branch from the main and copy what you have to the new branch and submit a new pull request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._